obstacle_range: 5.0
raytrace_range: 6.0
# TODO: Measaure exact numbers
footprint: [[0.3, 0.3], [-0.3, 0.3], [-0.3, -0.3], [0.3, -0.3]]
inflation_radius: 0.55
plugins: []

observation_sources: point_cloud_sensor

point_cloud_sensor: { sensor_frame: laser, data_type: PointCloud2, topic: /velodyne_points, marking: true, clearing: true}